//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.DaltonPonder.sa.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.DaltonPonder.sa.Shared.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EC-Council&apos;s Certified Ethical Hacker (CEH).
        /// </summary>
        public static string Home_CEHCertificate {
            get {
                return ResourceManager.GetString("Home.CEHCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certifications.
        /// </summary>
        public static string Home_CertificationsHeader {
            get {
                return ResourceManager.GetString("Home.CertificationsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.S. Computer Information Systems.
        /// </summary>
        public static string Home_EducationCC {
            get {
                return ResourceManager.GetString("Home.EducationCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string Home_EducationHeader {
            get {
                return ResourceManager.GetString("Home.EducationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.S. Cybersecurity &amp; Information Assurance.
        /// </summary>
        public static string Home_EducationWGU {
            get {
                return ResourceManager.GetString("Home.EducationWGU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beyond my professional pursuits, I find fulfillment and balance in a diverse array of hobbies and interests. My paramount joy lies in spending quality time with my family, cherishing moments that create lasting bonds and memories. Immersed in the transformative power of music, I often find solace in its melodies, enriching my days with a soundtrack that resonates with my spirit..
        /// </summary>
        public static string Home_GetToKnowMe1 {
            get {
                return ResourceManager.GetString("Home.GetToKnowMe1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a tech enthusiast, I indulge in the world of computer games, navigating virtual realms that challenge and captivate my mind. Outside the digital sphere, I channel my energy into the disciplined art of boxing, a physical endeavor that not only keeps me fit but instills a sense of focus and determination..
        /// </summary>
        public static string Home_GetToKnowMe2 {
            get {
                return ResourceManager.GetString("Home.GetToKnowMe2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In my continuous quest for personal development, I am dedicated to learning Spanish, opening doors to cultural understanding and global connections. Exploring the philosophical depths, I engage in the study of Stoicism, embracing its timeless principles for resilience and tranquility..
        /// </summary>
        public static string Home_GetToKnowMe3 {
            get {
                return ResourceManager.GetString("Home.GetToKnowMe3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finally, amidst the ebb and flow of life, I find solace in the written word. Reading, for me, is not just a pastime but a journey into different worlds, ideas, and perspectives. These diverse interests weave a tapestry that shapes my character, fostering a well-rounded and engaged approach to both personal and professional spheres..
        /// </summary>
        public static string Home_GetToKnowMe4 {
            get {
                return ResourceManager.GetString("Home.GetToKnowMe4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get To Know Me..
        /// </summary>
        public static string Home_GetToKnowMeHeader {
            get {
                return ResourceManager.GetString("Home.GetToKnowMeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Developer..
        /// </summary>
        public static string Home_HeroMessage1 {
            get {
                return ResourceManager.GetString("Home.HeroMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# Full-Stack..
        /// </summary>
        public static string Home_HeroMessage2 {
            get {
                return ResourceManager.GetString("Home.HeroMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitefinity Dev..
        /// </summary>
        public static string Home_HeroMessage3 {
            get {
                return ResourceManager.GetString("Home.HeroMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am Dalton Ponder..
        /// </summary>
        public static string Home_IAmDaltonPonder {
            get {
                return ResourceManager.GetString("Home.IAmDaltonPonder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With a passion for collaboration and a friendly demeanor, I thrive on helping others and working seamlessly within a team. My educational journey led me to achieve a bachelor&apos;s degree in Computer Information Systems from Columbia College, followed by a master’s degree in Cybersecurity and Information Assurance from Western Governor’s University. Complementing my academic prowess, I earned the esteemed Certified Ethical Hacker certificate from the EC-Council..
        /// </summary>
        public static string Home_Introduction {
            get {
                return ResourceManager.GetString("Home.Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently, I contribute my expertise as a Web Developer at Smooth Fusion in Lubbock, TX. Specializing in Progress Sitefinity Content Management System (CMS) solutions, I bring a wealth of knowledge and a dedication to creating innovative and secure web solutions for clients. My commitment to excellence extends beyond the code, as I continue to foster a collaborative and supportive work environment for the entire team..
        /// </summary>
        public static string Home_Introduction2 {
            get {
                return ResourceManager.GetString("Home.Introduction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress Sitefinity Certified Developer.
        /// </summary>
        public static string Home_SitefinityDevCertificate {
            get {
                return ResourceManager.GetString("Home.SitefinityDevCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome | DaltonPonder.com.
        /// </summary>
        public static string Home_Title {
            get {
                return ResourceManager.GetString("Home.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string Home_WelcomeMessage {
            get {
                return ResourceManager.GetString("Home.WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional Photo of Dalton Ponder.
        /// </summary>
        public static string Images_DaltonPonderAltText {
            get {
                return ResourceManager.GetString("Images.DaltonPonderAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect With Me.
        /// </summary>
        public static string MainLayout_ConnectWithMe {
            get {
                return ResourceManager.GetString("MainLayout.ConnectWithMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub Account Link.
        /// </summary>
        public static string MainLayout_GitHubTitle {
            get {
                return ResourceManager.GetString("MainLayout.GitHubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkedIn Account Link.
        /// </summary>
        public static string MainLayout_LinkedInTitle {
            get {
                return ResourceManager.GetString("MainLayout.LinkedInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string SelectUICultureComponent_ButtonText {
            get {
                return ResourceManager.GetString("SelectUICultureComponent.ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Spanish.
        /// </summary>
        public static string SelectUICultureComponent_ButtonTitle {
            get {
                return ResourceManager.GetString("SelectUICultureComponent.ButtonTitle", resourceCulture);
            }
        }
    }
}
